apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::187058103951:role/eksctl-eksctl-dejm-nodegroup-ng-9-NodeInstanceRole-1R3BJN2X23CO9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::187058103951:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-01T01:18:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1588"
  uid: 2f3dcea6-1c67-4db4-bd49-e2314340968f
